untuk inisialisasi library yang digunakan

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pds

dataset = pds.read_csv('exam1.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[['female' 'group D' 'some college' ... 59 70.0 78]
 ['male' 'group D' "associate's degree" ... 96 93.0 87]
 ['female' 'group D' 'some college' ... 57 nan 77]
 ...
 ['female' 'group A' 'high school' ... 67 86.0 86]
 ['male' 'group E' 'high school' ... 80 72.0 62]
 ['male' 'group D' 'high school' ... 58 47.0 45]]


In [5]:
print(y)

['completed' 'none' 'none' 'none' 'none' 'none' 'none' 'none' 'none'
 'completed' 'none' 'none' 'none' 'none' 'none' 'none' 'none' 'none'
 'none' 'completed' 'none' 'completed' 'none' 'none' 'completed' 'none'
 'none' 'none' 'none' 'none' 'completed' 'none' 'completed' 'none'
 'completed' 'none' 'none' 'completed' 'completed' 'none' 'completed'
 'completed' 'none' 'none' 'none' 'none' 'completed' 'completed' 'none'
 'completed' 'completed' 'completed' 'none' 'completed' 'none' 'none'
 'none' 'completed' 'none' 'none' 'completed' 'completed' 'none' 'none'
 'none' 'none' 'none' 'completed' 'none' 'none' 'completed' 'completed'
 'none' 'completed' 'completed' 'none' 'completed' 'none' 'completed'
 'none' 'none' 'completed' 'none' 'completed' 'none' 'none' 'completed'
 'none' 'none' 'none' 'completed' 'none' 'none' 'none' 'none' 'completed'
 'completed' 'none' 'completed' 'none' 'none' 'none' 'none' 'none' 'none'
 'none' 'completed' 'none' 'completed' 'none' 'completed' 'none'
 'completed'

untuk menghilangkan missing values

In [35]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 5:8])
X[:, 5:8] = imputer.transform(X[:, 5:8])

In [36]:
print(X)

[[1.0 0.0 'group D' ... 59.0 70.0 78.0]
 [0.0 1.0 'group D' ... 96.0 93.0 87.0]
 [1.0 0.0 'group D' ... 57.0 70.37637637637637 77.0]
 ...
 [1.0 0.0 'group A' ... 67.0 86.0 86.0]
 [0.0 1.0 'group E' ... 80.0 72.0 62.0]
 [0.0 1.0 'group D' ... 58.0 47.0 45.0]]


untuk encoding data ke matriks

In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [38]:
print(X)

[[0.0 1.0 0.0 ... 59.0 70.0 78.0]
 [1.0 0.0 1.0 ... 96.0 93.0 87.0]
 [0.0 1.0 0.0 ... 57.0 70.37637637637637 77.0]
 ...
 [0.0 1.0 0.0 ... 67.0 86.0 86.0]
 [1.0 0.0 1.0 ... 80.0 72.0 62.0]
 [1.0 0.0 1.0 ... 58.0 47.0 45.0]]


untuk encoding label atau y

In [39]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [40]:
print(y)

[0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 0 1 0 1 0 1 1
 0 0 1 0 0 1 1 1 1 0 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 0 1 1 0 0 1 0
 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 1 0 1 1 1 1 0 0 1 0 1 1 1 1 1 1 1 0 1 0 1 0
 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 0 1 1 1 1 1 0 0 0 1 1 1 0 0 1 1 1 1 0 0 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0
 1 1 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 0 1 1 1 0
 0 1 1 1 0 1 1 1 0 1 1 1 0 1 0 0 0 1 0 1 1 1 0 0 0 1 0 1 1 1 0 0 1 1 1 0 0
 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1
 0 1 1 0 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 1 1 1
 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 0 1 0 0 1 0 1 1
 1 0 0 1 1 1 1 0 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1
 1 0 1 0 1 1 0 1 1 1 1 1 0 1 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 1 1 1 0
 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 0 1 1 0 1 0 0 0 1 1 0 1 1 1 1
 1 1 1 1 0 1 0 0 0 1 0 1 

untuk membagi data ke training dan test set dengan data test 20% dan data train 80%

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [42]:
print(X_train)

[[0.0 1.0 0.0 ... 72.0 85.0 81.0]
 [0.0 1.0 0.0 ... 82.0 97.0 90.0]
 [1.0 0.0 1.0 ... 28.0 27.0 23.0]
 ...
 [1.0 0.0 1.0 ... 79.0 72.0 72.0]
 [0.0 1.0 0.0 ... 78.0 78.0 82.0]
 [1.0 0.0 1.0 ... 68.0 66.0 72.0]]


In [43]:
print(X_test)

[[1.0 0.0 1.0 ... 49.0 49.0 43.0]
 [1.0 0.0 1.0 ... 72.0 73.0 75.0]
 [0.0 1.0 0.0 ... 38.0 45.0 44.0]
 ...
 [1.0 0.0 1.0 ... 55.0 50.0 47.0]
 [1.0 0.0 1.0 ... 59.0 68.0 66.0]
 [1.0 0.0 1.0 ... 74.0 67.0 67.0]]


In [44]:
print(y_train)

[1 1 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1
 0 1 1 0 1 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 0 1
 1 0 1 0 0 0 1 1 0 1 0 1 1 0 0 1 1 1 1 0 0 1 1 0 1 1 0 0 0 1 0 1 1 0 1 1 1
 0 1 0 1 1 1 0 0 0 0 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 0 1 1 1 1 1
 1 1 1 0 1 1 0 0 0 0 1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 0 1 1 1 1 1 1 1 0 1 0
 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1
 1 0 1 0 0 1 0 1 0 0 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 0 1 0 1 1 0 1 0 1 1 1 1 1 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1 1 0
 0 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 1 1 1
 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 0 0 0 1 0 0 0 1 1 1 1 1 1 1
 0 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 0 1 0 1 0 0 1 0 1 1 0
 1 0 1 0 0 0 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 1 0 1 0 1 1 0 1 0 0 1 0
 0 1 0 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 1 0
 1 1 1 1 1 0 0 1 1 1 1 1 

In [45]:
print(y_test)

[1 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0
 0 1 0 1 0 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 1 0 1 1 1 1 1
 0 1 0 1 1 1 1 1 0 0 1 0 1 0 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0 0 1 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 1 1 1
 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 0 0 1 1 0 1 0 1 1 1 0 1 1 1 0 1 0 0
 1 0 1 1 0 1 1 1 1 0 1 1 1 0 1]


untuk melakukan scaling untuk memperkecil skala yang terdapat pada data

In [50]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 6:9] = sc.fit_transform(X_train[:, 6:9])
X_test[:, 6:9] = sc.transform(X_test[:, 6:9])

In [51]:
print(X_train)

[[0.0 1.0 0.0 ... 0.2647815023278211 1.031276094627781 0.787773510491133]
 [0.0 1.0 0.0 ... 0.9055110905379147 1.8801357798225589 1.38658783434419]
 [1.0 0.0 1.0 ... -2.5544286857965903 -3.0715457171469795
  -3.0712521321174564]
 ...
 [1.0 0.0 1.0 ... 0.7132922140748866 0.1116781023334381
  0.18895918663807598]
 [0.0 1.0 0.0 ... 0.6492192552538772 0.536107944930827 0.8543084353636948]
 [1.0 0.0 1.0 ... 0.008489667043783766 -0.3127517402639509
  0.18895918663807598]]


In [52]:
print(X_test)

[[1.0 0.0 1.0 ... -1.208896550555394 -1.515302960956553
  -1.7405536346662187]
 [1.0 0.0 1.0 ... 0.2647815023278211 0.18241640943300294
  0.38856396125576165]
 [0.0 1.0 0.0 ... -1.9136990975864967 -1.7982561893548124
  -1.6740187097936567]
 ...
 [1.0 0.0 1.0 ... -0.8244587976293378 -1.4445646538569883
  -1.474413935175971]
 [1.0 0.0 1.0 ... -0.5681669623453004 -0.17127512606482123
  -0.21025036259729532]
 [1.0 0.0 1.0 ... 0.3929274199698398 -0.24201343316438606
  -0.14371543772473344]]
